add 2_4_4/server.rs
yuk1ty/learning-systems-programming-in-rust pull request #20
Opened 2021-04-29 14:52 UTC by hide5stm

2.4.4 完了です。

2021-04-29 23:54 UTC, laysakura requested changes

2021-04-29 23:54 UTC, laysakura commented on chapter2/src/2_4_4/server.rs
> +    writeln!(stream, "HTTP/1.1 200 OK").unwrap();
`.unwrap()` の使用はできる限り控えたほうが良いです。

シンプルなポリシーとしては、
main関数やtestの関数など、最上流で「このErr型は捨ててpanicにしてもいいや」と判断できる箇所のみで使うべき
と考えて良いと思います。

今回は

```rust
fn get_operation(stream: &mut TcpStream) -> std::io::Result<()> {
    let body = "HTTP server sample";
    writeln!(stream, "HTTP/1.1 200 OK")?;
    ...
```

とし、 `?` で Errを短絡returnするのが書きやすいし読みやすいしErrを呼び出し側に伝播できて良いと思います。

2021-04-29 23:54 UTC, laysakura commented on chapter2/src/2_4_4/server.rs
> +    writeln!(stream, "Content-Type: text/html; charset=UTF-8").unwrap();
[nits] HTMLのフォーマットには沿っていないので `text/plain` のほうが良いかと思います。

2021-04-29 23:54 UTC, laysakura commented on chapter2/src/2_4_4/server.rs
> +    }
ここも `fn handle_client(stream: TcpStream) -> std::io::Result<()> {` とした上で、
`reader.read_line(&mut first_line)?;` で良いかと思います。

2021-04-29 23:54 UTC, laysakura commented on chapter2/src/2_4_4/server.rs
> +    let listener = TcpListener::bind("127.0.0.1:8080").unwrap();
main() も同様に任意のResult型を返すようにできます。

```rust
fn main() -> std::io::Result<()> {
    let listener = TcpListener::bind("127.0.0.1:8080")?;
```

として、Err型が返ってきたときの処理（stderrにstacktraceを流すなど）をrustの処理系に任せるのも一つのよく使われる手です。
もちろん、main() においてはErrが起きたときの挙動をプログラマ側で制御し切るというのも良い作法です。
ただ `.unwrap()` するだけなら `-> Result<()>` と `?` を使ったほうが良いかと思います。

2021-04-29 23:54 UTC, laysakura commented on chapter2/src/2_4_4/server.rs
> +    }
main() の返り値を `std::io::Result<()>`  にしていれば、

```rust
    for stream in listener.incoming() {
        handle_client(stream?)
    }
```

とスッキリ書けるはずです。

2021-04-30 00:08 UTC, laysakura commented
CIの `lint` が失敗している件はおそらく私の作業不足が原因で、 https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/21 で対応中です 🙇

2021-04-30 00:33 UTC, hide5stm commented on chapter2/src/2_4_4/server.rs
> +    writeln!(stream, "HTTP/1.1 200 OK").unwrap();
ありがとうございます。初心者なので、指摘ビシバシお願いします。
ご紹介の資料などで勉強してきます。

2021-04-30 04:51 UTC, hide5stm commented
ご指摘のエラー処理修正しました。

2021-04-30 05:40 UTC, laysakura requested changes
指摘した箇所が修正されていることは確認しました。

[CIのlintジョブ](https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/20/checks?check_run_id=2472884966) で指摘されている箇所の修正をお願いします。
手修正はいらず、


```bash
cargo fmt --all
```

でOKのはずです。

2021-04-30 06:51 UTC, laysakura approved these changes
👏

2021-04-30 06:52 UTC, hide5stm commented
環境が古かったようで1.51にしてcargo fmt動かせました。お手数おかけしました

2021-04-30 08:26 UTC, yuk1ty commented
refs #5

2021-04-30 08:30 UTC, yuk1ty approved these changes
ありがとうございます！😄

2021-05-01 05:31 UTC, merged