3.4の実装を行う
yuk1ty/learning-systems-programming-in-rust pull request #32
Opened 2021-04-30 16:42 UTC by higumachan

2021-04-30 20:40 UTC, laysakura commented on chapter3/src/main.rs
> +    let mut conn = TcpStream::connect("ascii.jp:80").unwrap();
(Draft取れたら全体見させていただくとして、たまたま目に入った部分を...)

ascii.jp に繋ぐのはマナー上避けたほうが良いと思います。
『Goなら...』のほうは元々[ASCIIで連載](https://ascii.jp/serialarticles/1235262/)している経緯から ascii.jp を気軽に使っているものと思われます。

example.com ならこういう場合の例示に使って良いことがRFCに定められています。
https://tools.ietf.org/html/rfc2606#section-3

2021-05-01 03:06 UTC, higumachan commented
コード中にも書いているのですが、3_4_4に関してはRustではそもそもReadAtがない問題があります。(Read + Seekが近い？)

近しいものとしては

- https://docs.rs/crate/positioned-io/0.2.2
- https://docs.rs/crate/io-at/0.1.4

も見つけられましたがどちらも実質標準という感じではないと思います。

方針としては以下が考えられますがどういたしましょうか？

1. 実装をスキップする
2. ReadAtを自分で定義して、strings.Reader, bytes.Reader相当の実装を作る

僕的には本書でも「BufReader使っておけば…」のように書かれているので、1かなと思っています。

2021-05-01 03:58 UTC, yuk1ty commented
これとか近いんじゃないかなと思いましたが、すみません、私もあまり Go の ReadAt を理解していないまま書いています🙇‍♀️
https://doc.rust-lang.org/std/io/struct.Cursor.html

2, 3, 4 は Go 特有の事情を説明する箇所が結構多く、迷ったら `unimplemented` にして飛ばしてしまうのはありかと思っています！なので、`Cursor` が厳しそうだったら、一旦1で大丈夫です。

2021-05-01 04:00 UTC, yuk1ty reviewed
nitpicking🙇‍♀️

2021-05-01 04:00 UTC, yuk1ty commented on chapter3/src/3_4_4/main.rs
> +    unimplement!("rustにgoのio.ReadAtに相当するものが実質std(要定義)までを含めても見受けられないので実装をスキップ");
`unimplemented!` ですね。

2021-05-01 04:00 UTC, yuk1ty commented on chapter3/src/3_4_2/wasCopied.rs
> +use std::fs::File;
wasCopied.rs → was_copied.rs

2021-05-01 04:55 UTC, higumachan commented
> これとか近いんじゃないかなと思いましたが、すみません、私もあまり Go の ReadAt を理解していないまま書いています
> https://doc.rust-lang.org/std/io/struct.Cursor.html
> 
> 2, 3, 4 は Go 特有の事情を説明する箇所が結構多く、迷ったら `unimplemented` にして飛ばしてしまうのはありかと思っています！なので、`Cursor` が厳しそうだったら、一旦1で大丈夫です。

そうですね、Cursorは適当なbufferに対して`Read`と`Seek`が実装されてるので一番近いと思ってます。

`bytes.Reader`は`Cursor<Vec<u8>>`とほとんど同じだと思っています。
`strings.Reader`は`Cursor<String>`の実装はないので自分でラップして作る感じかなと思います。

僕もgoを書かないので`io.ReadAt`については一旦`Read + Seek`として考えて実装して詳しい人のレビューがあるのを祈ろうかと思います。

2021-05-01 12:53 UTC, yuk1ty reviewed
ありがとうございます！

細かいですが、いくつか修正をお願いしたいです。

2021-05-01 12:53 UTC, yuk1ty commented on chapter3/src/3_4_1/main.rs
> +fn main() {
main 関数を下記のようにしておいて、

```suggestion
fn main() -> std::io::Result<()> {
```

2021-05-01 12:53 UTC, yuk1ty commented on chapter3/src/3_4_1/main.rs
> +        match stdin().read(&mut buffer) {
ここのパターンマッチングは

```suggestion
        let n = stdin().read(&mut buffer)?;
        if n == 0 {
                println!("EOF");
                break;
        }
        println!(
                    "size={} input'{}'",
                    size,
                    std::str::from_utf8(&buffer).unwrap()
        );
```

としておくほうがよさそうに思いました。

`read` 関数は Go のように `EOF` だった際にはエラーを返しません。

返り値が `Ok(0)` だったときに実質 `EOF` に到達したとみなせます。

rustdoc には

1. Reader が EOF に到達した
2. バッファがそもそも0バイトだった

のどちらかのケースを示すと書かれています。Rust 的な対応としてはしたがって、結果が 0 だったかどうかで EOF かどうかを判定しておいて、残りのエラーは検出時点で伝播させておいて済ませておく、がベストかなと思っています。

2021-05-01 12:53 UTC, yuk1ty commented on chapter3/src/3_4_3/main.rs
> +    fn new(mut reader: R) -> Result<Self, Error> {
この関数内の `unwrap` はできれば `?` で伝播させたいです。最後 main 関数などでまとめて処理してさばきたいためです。`unwrap` は、main 関数や test のときなど、Err 型をパニックさせて捨ててもいいと判断できる場所でのみ使用したいです。

2021-05-01 12:53 UTC, yuk1ty commented on chapter3/src/3_4_3/main.rs
> +    fn new(mut reader: R) -> Result<Self, Error> {
異なるエラー型をきれいにまとめている例として、下記のプルリクエストが参考になるかもしれません。
https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/23/files

2021-05-01 12:53 UTC, yuk1ty commented on chapter3/src/3_4_3/main.rs
> +    std::io::copy(&mut res.body, &mut stdout());
unwrap が必要ですかね？

```suggestion
    std::io::copy(&mut res.body, &mut stdout()).unwrap();
```

2021-05-01 12:55 UTC, yuk1ty commented
`ReadAt` は私も手元で動かしながら確認しています。少々お待ち下さい🙏 `Cursor` で特に問題ないんじゃないかなーと思っています！

2021-05-01 13:05 UTC, higumachan commented on chapter3/src/3_4_1/main.rs
> +        match stdin().read(&mut buffer) {
こっちのほうがスッキリはするので書き換えたいとおもいます。

2021-05-01 13:05 UTC, higumachan commented on chapter3/src/3_4_3/main.rs
> +    fn new(mut reader: R) -> Result<Self, Error> {
了解です。
参照のプルリクのような方法もあると思いますが、利用可能でしたらanyhowあたりを利用してもよろしいでしょうか？

2021-05-01 13:27 UTC, higumachan commented
@yuk1ty コメントありがとうございます、修正しました。

2021-05-02 10:36 UTC, laysakura requested changes

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_1/main.rs
> +        ); // rustはStringがUTF-8だから若干違うのはしょうがない？
何と比べて「違う」のかがわかりませんでした。

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_2/was_copied.rs
> +use std::fs::File;
このファイルはただの 3_4_2/main.rs のコピー先だからコミットしないほうが良いと思います。

あと、元の https://github.com/yurakawa/learn-system-programming-with-go/blob/master/ch3/s4-2/main.go の実装が良くないと思いますが、コピー先をソースツリー的に意味の有りそうな `.rs` にしないほうが良いと思います。

`copied.txt` などで良いと思います。

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_2/main.rs
> +    std::io::copy(&mut src_file, &mut dest_file).unwrap();
main() で unwrap するのはよく考えていれば良いと思いますが、ここでは全ての io::Result を unwrap しているので、 `main() -> io::Result<()>` として

```rust
let mut src_file = File::open("main.rs")?;
```

などにしたほうが良いと思います。

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_3/main.rs
> +    std::io::copy(&mut res.body, &mut stdout()).unwrap();
この main() も `-> io::Result<()>` にして、 `.unwrap()` よりも `?` を使ったほうが良さそうです。

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_3/main.rs
> +    body: Vec<u8>,
この文脈での `body` は HTTPボディ と混同されやすいです。HTTPヘッダは `name` と `value` で構成されるので、ここは `value` が良いと思います。

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_3/main.rs
> +    body: Vec<u8>,
[HTTPヘッダのvalueにはASCIIが来ることを想定して良い](https://stackoverflow.com/a/4410331/5307621) ので、 `Vec<u8>` (任意のバイト列) ではなく `String` (UTF-8文字列) のほうが適切に強く制約できて、かつ取り回しが良いと思います。

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_3/main.rs
> +struct HeaderOwn {
[質問] ここの `Own` はどういう気持ちでつけた名称でしょうか？

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_3/main.rs
> +            let status = resp.parse(&buf)?;
ちょっと読み違えているかもしれませんが、 `buf` は必要でしょうか？

この行で `resp.parse(line.as_bytes())`  とすれば `buf` は要らないようにも見えます。

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_3/main.rs
> +            let mut resp = Response::new(&mut headers);
[nits] `30` というのはマジックナンバーなので「30個くらいで十分と考えた」みたいなコメントを書いておくと親切だと思います。

---
（独り言） 
httpparse::Response って気持ち悪いインターフェイスしてますね。なんでこちらがスタック領域で用意した（しかも EMPTY_HEADER とかいう定数使って）arrayを渡してやらないといけないのか...

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/3_4_4/main.rs
> +}
あまり良くわかってないですが、 `Seek` トレイトを実装した理由はなんですか？

実装するとした場合、RustにおけるStringは「UTF-8文字列」という意味があるので、 `pos == 1` は「UTF-8における一文字目の後」になるかと思います。

例えば `"あいう"`` という文字列があった場合、 `pos == 1` は `あ` と `い` の間へのseekを期待しますが、この実装だと（3バイト文字である） `あ` の2バイト目、つまりUTF-8としては意味のない区切り箇所になるのではないでしょうか？

2021-05-02 10:36 UTC, laysakura commented on chapter3/src/main.rs
> +}
このファイルは不要だと思います。

2021-05-02 10:38 UTC, laysakura commented on chapter3/src/3_4_4/main.rs
> +}
>  Seek トレイトを実装した理由はなんですか？

ごめんなさい 🙇 
https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/32#issuecomment-830505999 に記載がありましたね。

2021-05-03 01:59 UTC, higumachan commented on chapter3/src/3_4_1/main.rs
> +        ); // rustはStringがUTF-8だから若干違うのはしょうがない？
意図としてはGoの`string`は確かリテラルならばUTF8だけど基本的には任意のバイト列を入れることが可能だったと認識しているのでっていう意図でした。

2021-05-03 02:05 UTC, higumachan commented on chapter3/src/3_4_2/main.rs
> +    std::io::copy(&mut src_file, &mut dest_file).unwrap();
こちらの書き方に変更するのは問題ないのですが、main関数内で`unwrap`をするのに比べての良さをあまり理解できていないので教えて頂いてもよろしいでしょうか？

僕はmain関数内では`unwrap`のほうがエラー箇所が行で出るのでmain関数内やエントリポイント内では`unwrap`を利用するほうを利用することが多いです。

2021-05-03 02:24 UTC, higumachan commented on chapter3/src/3_4_3/main.rs
> +struct HeaderOwn {
気持ちとしては、
httparseのHeaderは参照をベースにして`name`と`value`をを持っている構造体なので、こちらはVecやStringで所有権を持つような構造体なのでOwnをつけています。

2021-05-03 02:31 UTC, higumachan commented on chapter3/src/3_4_3/main.rs
> +            let status = resp.parse(&buf)?;
```rust
let mut buf = vec![];
let headers = loop {
    let mut line = String::new();
    reader.read_line(&mut line)?;
    buf.extend_from_slice(&line.as_bytes());

    let mut headers = [EMPTY_HEADER; 30];
    let mut resp = Response::new(&mut headers);
    let status = resp.parse(&buf)?;
    if status.is_complete() {
        break resp
            .headers
            .iter()
            .map(|h| HeaderOwn {
                name: h.name.to_string(),
                body: h.value.to_vec(),
            })
            .collect();
    }
}
```

ここに関してはReaderの頭からbufに行を追加していき、headerとしてparseが成功(Complete)するまでbufに追加するというような処理を書いているためbufは必要かと思います。(HTTP Headerのparseは複数行にまたがるのでこうしています)

ちなみに、httparseは初めて使っていおり使い方があまりこなれていないのでもっと良い書き方はあるかもしれません。

2021-05-03 02:34 UTC, higumachan commented on chapter3/src/3_4_3/main.rs
> +            let mut resp = Response::new(&mut headers);
そうですね。コメントを書いておきます。

> 
> （独り言）
> httpparse::Response って気持ち悪いインターフェイスしてますね。なんでこちらがスタック領域で用意した（しかも EMPTY_HEADER とかいう定数使って）arrayを渡してやらないといけないのか...

これは僕も思いました。
`nostd`環境や`core`環境(私はほとんど書いたことないですが)に対応するための書き方なのかな？と思っていました。

2021-05-03 11:26 UTC, laysakura commented on chapter3/src/3_4_2/main.rs
> +    std::io::copy(&mut src_file, &mut dest_file).unwrap();
説明不足で申し訳ございません 🙇 

> main関数内でunwrapをするのに比べての良さ

mainから関数分割した際のコピペしやすさ程度の弱い良さです。

> 僕はmain関数内ではunwrapのほうがエラー箇所が行で出るのでmain関数内やエントリポイント内ではunwrapを利用するほうを利用することが多いです。

このポイントはなるほどと思いました。
一応 `?` でも `RUST_BACKTRACE=1` 環境変数を設定すればバックトレースとしてはエラー箇所を辿れるのですが、そんなことせずに見えるほうが便利ですね。

@higumachan さんの仰るメリットのほうが大きいと感じましたので、このコメントは取り下げます。

2021-05-03 11:26 UTC, laysakura commented on chapter3/src/3_4_3/main.rs
> +struct HeaderOwn {
なるほど httparse との対比でしたか。理解しました。

2021-05-03 11:26 UTC, laysakura commented on chapter3/src/3_4_3/main.rs
> +            let status = resp.parse(&buf)?;
> headerとしてparseが成功(Complete)するまでbufに追加する

理解しました 🙏

2021-05-03 11:26 UTC, laysakura commented on chapter3/src/3_4_3/main.rs
> +            let mut resp = Response::new(&mut headers);
GitHubのREADMEに

> Avoids allocations. No copy. Fast.

と書いてありました。allocationを利用者に任せているんですね。
ライブラリの中で `Vec<Header>` を（ヒープ上に）確保してその所有権を返したほうが使いやすいインターフェイスになるので、HTTPパースをカリカリにチューニングしたい人向けですね。

2021-05-03 11:26 UTC, laysakura commented on chapter3/src/3_4_4/main.rs
> +}
@higumachan 
> 実装するとした場合、RustにおけるStringは「UTF-8文字列」という意味があるので、 pos == 1 は「UTF-8における一文字目の後」になるかと思います。
> 
> 例えば "あいう"`` という文字列があった場合、 pos == 1はあといの間へのseekを期待しますが、この実装だと（3バイト文字である）あ` の2バイト目、つまりUTF-8としては意味のない区切り箇所になるのではないでしょうか？

この点はどうでしょうか？

2021-05-03 13:42 UTC, higumachan commented on chapter3/src/3_4_2/main.rs
> +    std::io::copy(&mut src_file, &mut dest_file).unwrap();
🙇

2021-05-03 13:51 UTC, higumachan commented on chapter3/src/3_4_4/main.rs
> +}
そちらの点に関しては問題は存在していると思います。

Goの実装でも
https://golang.org/pkg/strings/#Reader

同じ問題は持っているかと思いますのでportingとしては問題ないのかなと思っています。

おっしゃるとおり"あいう"で`pos == 1`のときに"あ"と"い"の間が直感的であるのは確かですが。
あくまで、文字列の世界(雑な言葉ですいません)での話かなと思っています。
バイト列の世界では`pos == 1`が"あ"の中に存在するのは当たり前のことかと思います。

`StringReader`や`strings.Reader`に関しては文字列の世界からバイト列の世界に持ってくるものかなと認識しているので現状の実装でも問題ないかと思っています。(元ソースに利用例がないので僕の妄想の部分もあるかと思いますが)

2021-05-03 22:39 UTC, laysakura commented on chapter3/src/3_4_4/main.rs
> +}
> Goの実装でも
> https://golang.org/pkg/strings/#Reader
> 
> 同じ問題は持っているかと思いますのでportingとしては問題ないのかなと思っています。

たしかにそうですね。確認しました。

> StringReaderやstrings.Readerに関しては文字列の世界からバイト列の世界に持ってくるものかな

どうやらそうみたいですね。
そしたらbytes.Readerで事足りるのに、strings.Readerなんて半端なものを... 🤔 とあまり良く知らないGoに対して思いました。

---
この実装で問題ないと思うので、Resolveします 🙏

2021-05-03 22:39 UTC, laysakura approved these changes

2021-05-04 13:19 UTC, yuk1ty requested changes
@higumachan CI にてビルドエラーが起きてしまっていたので、修正をお願いします！

2021-05-04 13:19 UTC, yuk1ty commented on chapter3/Cargo.toml
> +[dependencies]
コンフリクトを解消してもらったタイミングとかで、`[dependencies]` が2箇所できちゃったかもです🙏 これが原因でビルドエラーが起きてしまっているので、お手数ですが上のものと下のものをマージして1つにしてもらってもいいでしょうか？

2021-05-04 15:22 UTC, higumachan commented on chapter3/Cargo.toml
> +[dependencies]
こちら修正いたしました。

2021-05-05 13:17 UTC, yuk1ty approved these changes

2021-05-06 10:39 UTC, yuk1ty commented
マージしますね！

2021-05-06 10:39 UTC, merged