implement chapter3_9 other than problem 3_9_6
yuk1ty/learning-systems-programming-in-rust pull request #33
Opened 2021-05-01 09:00 UTC by k-nasa

ref: https://github.com/yuk1ty/learning-systems-programming-in-rust/issues/16

3.9節の1~5までの実装を行いました。

3.9.6に関しては、golangだとio.multiReader, io.SectionReaderを使って得問題のようで、Rust標準には代替のものがボクの知る限りありません。multiReader, SectionReaderを実装するのは骨が折れますし問題の趣旨からずれそうなので一旦スキップしました。

## Proof
以下動作確認ログになります。

<details>

### 3.9.1
```
❯ cargo run -p chapter3 --bin 3_9_1 chapter3/src/3_9_1/old.txt new.txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/3_9_1 chapter3/src/3_9_1/old.txt new.txt`

❯ cat new.txt
old text
```

### 3.9.2

```
❯ cargo run -p chapter3 --bin 3_9_2
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/3_9_2`

❯ wc -c random.txt
    1024 random.txt
```

### 3.9.3

```
❯ cargo run -p chapter3 --bin 3_9_3
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/3_9_3`

❯ unzip file.zip
Archive:  file.zip
  inflating: file.txt

❯ cat file.txt
zipzipzipzipzipzipzipzipzipzipzipzipzipzipzipzip
```

### 3.9.4

```
❯ cargo run -p chapter3 --bin 3_9_4
```

localhost:8080にアクセスすると次のファイルがダウンロードできる

<img width="786" alt="スクリーンショット 2021-05-01 17 53 58" src="https://user-images.githubusercontent.com/23740172/116776927-3bd46380-aaa6-11eb-959e-67732c7987bd.png">

### 3.9.5

```
❯ echo "testtest" > test.txt

❯ cargo run -p chapter3 --bin 3_9_5
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/3_9_5`

❯ cat new_test.txt
test
```

</details>

2021-05-01 15:04 UTC, yuk1ty approved these changes
ありがとうございます！😃

2021-05-02 19:08 UTC, laysakura requested changes
全体的にほぼ良かったのですが、細かい点だけコメントしました 🙏

2021-05-02 19:08 UTC, laysakura commented on chapter3/src/3_9_1/old.txt
> +old text
せっかくコマンドライン引数でコピー元を指定する形になっているので、このファイルはコミットしないで良いと思います。

2021-05-02 19:08 UTC, laysakura commented on chapter3/src/3_9_2/main.rs
> +    }
[nits] こう書くとスッキリしますし、パフォーマンスも良いです（1024回のループ程度で気にすることはないですが）。

```suggestion
    let bytes = rand::thread_rng().gen::<[u8; 1024]>();
```

2021-05-02 19:08 UTC, laysakura commented on chapter3/src/3_9_5/main.rs
> +    let mut file = File::open("test.txt")?;
[nits] ここは

```suggestion
    let mut file = File::open("test.txt").expect(r#"動作には4バイト以上の "{}/test.txt" が必要です。"#, std::env::current_dir()?.display());
```

などとしてあげると親切かなと思います。

2021-05-03 07:16 UTC, k-nasa commented on chapter3/src/3_9_2/main.rs
> +    }
📝  なるほど。こんな書き方があるんですね！

2021-05-03 07:20 UTC, k-nasa commented on chapter3/src/3_9_1/old.txt
> +old text
確かに。不要ですね。
2e117ed Done!です。

2021-05-03 07:23 UTC, k-nasa commented
レビューありがとうございます 🙇  
指摘いただいた箇所の修正は終わりました！

2021-05-03 11:33 UTC, laysakura commented
@k-nasa 対応ありがとうございます。私のsuggestionを取り入れていただきましたが、空で書いたためそのままではビルドが通らずCIが落ちています...
動作確認 & commit & pushをお願いします。

2021-05-03 12:48 UTC, k-nasa commented
🙈  すみません。完全に脳死していました。
buildが通ることを確認しました。

2021-05-03 12:49 UTC, k-nasa commented on chapter3/src/3_9_2/main.rs
> +    rand::thread_rng().fill(&mut bytes);
https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/33#discussion_r624739452

docを見るに`gen`では最大で32要素しか埋められないらしく、`fill`を使うことにしました。

ref: https://docs.rs/rand/0.8.3/rand/trait.Rng.html#arrays-and-tuples

2021-05-03 21:51 UTC, laysakura commented on chapter3/src/3_9_2/main.rs
> +    rand::thread_rng().fill(&mut bytes);
そうなんですね 😮 勉強になりました 🙏

2021-05-03 21:52 UTC, laysakura approved these changes
🎉

2021-05-04 13:21 UTC, yuk1ty commented
マージします

2021-05-04 13:21 UTC, merged