4-2の実装を行う
yuk1ty/learning-systems-programming-in-rust pull request #35
Opened 2021-05-01 14:45 UTC by higumachan

#28

2021-05-04 11:12 UTC, laysakura requested changes

2021-05-04 11:12 UTC, laysakura commented on chapter4/src/4_2_1/main.rs
> +        done_tx.send(true);
```suggestion
        done_tx.send(true).await.unwrap();
```

が良いと思います。
元のコードだと、SendError が発生したときにメインスレッドが `done_rx.recv().await` で永遠にブロックする挙動になりそうです。

2021-05-04 11:12 UTC, laysakura commented on chapter4/src/4_2_4/main.rs
> +            chint.send(i).await;
このあたりもResultを捨てているので、SendErrorのケースでメインスレッド側がずっとブロックしてしまうと思います。

[ビルド時に警告が出ている](https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/35/checks?check_run_id=2490334861#step:3:139) ので確認してみてください。

2021-05-04 11:12 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    let (ctx, cancel) = WithCancel::new(); // context.Background()に関してあまり理解できていない
Goの `context.WithCancel` は引数に context を受け取ります。
現在既に呼び出し元から context をもらっているならその context を引数に渡すべきですが、リクエストの最初（main関数など）でコンテキストのルートになる箇所では context.Background() で空の context を作るようです。
（自分もあまり詳しくないですが[この記事](https://qiita.com/marnie_ms4/items/985d67c4c1b29e11fffc)を参照しました）

contextの本質はキーバリューのset/getですが、この `WithCancel` はその機能がありません。

WithCancelに:

- キーバリューのset/get機能をつける
- contextのツリーを構成する機能をつける
- cancelにメッセージを送ったときに、ツリーの子のcancelにもメッセージを送る

という機能はGoの `context.WithCancel` はできるので、追加の余地があるものだと思います。

---
また、ここでは WithCancel::new では2つ目の返り値で `oneshot::Sender<()>` をそのまま返していますが、 newtype パターンを使い、利用者に意図を伝わりやすくすること・型による制約を強くしてリファクタリングを用意にすることも重要です。

```rust
struct Canceler(oneshot::Sender<()>);

impl Canceler {
    async fn cancel(self) -> Result<(), oneshot::error::SendError> {
        self.0.send(()).await
    }
}
```

とかで十分かと思います。

2021-05-04 11:52 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    let (ctx, cancel) = WithCancel::new(); // context.Background()に関してあまり理解できていない
> また、ここでは WithCancel::new では2つ目の返り値で oneshot::Sender<()> をそのまま返していますが、 newtype パターンを使い、利用者に意図を伝わりやすくすること・型による制約を強くしてリファクタリングを用意にすることも重要です。

確かに、ここはnewtype パターン使った方が意図が伝わりやすくなりそうですね。

`cancel`メソッドでも良いかと思うのですが、Goの実装に近づけるならCancelerを`FnOnce`をimplしてCallableオブジェクトにするのが良いのかとは思いますが。

どう思いますかね？

2021-05-04 12:02 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    let (ctx, cancel) = WithCancel::new(); // context.Background()に関してあまり理解できていない
> Goの実装に近づけるならCancelerをFnOnceをimplしてCallableオブジェクトにするのが良い

そうですね。より良いと思います 👍

2021-05-04 12:22 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    let (ctx, cancel) = WithCancel::new(); // context.Background()に関してあまり理解できていない
まだ、`Fn*`へのimplはstableになってないみたいですので、`cancel`メソッドを生やす形にします。

https://github.com/rust-lang/rust/issues/29625

2021-05-04 15:18 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    let (ctx, cancel) = WithCancel::new(); // context.Background()に関してあまり理解できていない
> Goの context.WithCancel は引数に context を受け取ります。
現在既に呼び出し元から context をもらっているならその context を引数に渡すべきですが、リクエストの最初（main関数など）でコンテキストのルートになる箇所では context.Background() で空の context を作るようです。
（自分もあまり詳しくないですがこの記事を参照しました）
> 
> contextの本質はキーバリューのset/getですが、この WithCancel はその機能がありません。
> 
> WithCancelに:
> 
> キーバリューのset/get機能をつける
> contextのツリーを構成する機能をつける
> cancelにメッセージを送ったときに、ツリーの子のcancelにもメッセージを送る
> という機能はGoの context.WithCancel はできるので、追加の余地があるものだと思います。
> 
> 

こちらの話は実装を読んでみましたが少し腰を据えて実装したほうが良さそうだと思いました。

なんか、割とGoならではの実装でRust(というかtokio)で実装する場合は実装変わりそうだなと思いました。
ちょっと考えてみます。

2021-05-05 14:13 UTC, yuk1ty commented on chapter4/src/4_2_5/main.rs
> +    let (ctx, cancel) = WithCancel::new(); // context.Background()に関してあまり理解できていない
`WithCancel` をしっかり実装しきっちゃいたいですね。tokio で乗り切る際のネックになりそうなので！実装がそこそこ変わるかなと思っています。

> なんか、割とGoならではの実装でRust(というかtokio)で実装する場合は実装変わりそうだなと思いました。
> ちょっと考えてみます。

よろしくお願いします！

2021-05-06 13:53 UTC, higumachan commented
@laysakura @yuk1ty 

一旦、Goの実装をある程度模倣して実装してみました。

ほかでもよく利用するならlibに実装したほうがいいかもしれないですね。

2021-05-06 21:35 UTC, laysakura commented
@higumachan 最新のcommitが
> Contextは実装していない部分があるのでdead_codeが存在する。

で状況がちょっとわかっていないですが、review readyでしょうか？

> ほかでもよく利用するならlibに実装したほうがいいかもしれないですね。

Goの標準ライブラリにあるようなものを実装した場合には（他で使うか否かにかかわらず） lib に置いて良いと思います。
ただし lib に置くからには最低限 [doc test](https://doc.rust-lang.org/rustdoc/documentation-tests.html) か unit test はほしいところです。

2021-05-07 07:47 UTC, higumachan commented
> で状況がちょっとわかっていないですが、review readyでしょうか？

libへの分割を横においておくならば、review readyな状態です。

> Goの標準ライブラリにあるようなものを実装した場合には（他で使うか否かにかかわらず） lib に置いて良いと思います。
ただし lib に置くからには最低限 doc test か unit test はほしいところです。

unit testとかは`WithValue`とかの他のコンテキストも実装してからやったほうが良さそうだと思います。
一旦このPRはこのコードでマージして頂いて別PRでlibへの分割しようかと思うのですがどうでしょうか？

2021-05-07 11:50 UTC, laysakura commented
lib移しは別PRで、了解です。その形でレビューしていきます。

description更新と

![image](https://user-images.githubusercontent.com/498788/117445561-cbca4f80-af75-11eb-9fee-95f8e927900b.png)

の更新ボタン押してのレビューリクエストは随時行っていただけるとレビュワー的に助かります。

2021-05-07 11:55 UTC, higumachan commented
そんな機能あったんですね知らなかったです。
了解しました！

2021-05-07 12:05 UTC, higumachan commented
@laysakura 

現状の方針ではMutex周りだけは `unwrap` を利用しています。(他スレッドでpanicになったときは今回はただちにpanicで良いかと考えています。)

2021-05-07 12:23 UTC, laysakura requested changes
理解が難しかった部分もあり、いくつかコメントしました。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +#![allow(dead_code)]
allowせず、dead code部分を削除する（後にlibに移行するときに必要に応じて復活させる）では駄目でしょうか？
なるべく半端な状態をmasterに作らないほうが良いかと思い。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    fn deadline(&self, deadline: Instant, ok: bool);
(`&mut self` ではなく) `&self` を取ってかつ返り値も返さないとなると、有益なことは何もできない関数に見えますが、これで意図はあってますか？

（self が RefCell などの内部可変なフィールドを持っていれば状態の変化を起こせますが、Contextをimplする人への制約が強すぎる気がします）

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    fn value(&self, key: &ContextKey) -> Result<Arc<dyn Any>, ContextValueError>;
Arcな必要があるかがちょっとわかってません。

`-> Result<&dyn Any, ContextValueError>;`

では駄目でしょうか？（純粋な質問）

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    fn done(&self) -> Pin<Box<dyn Future<Output = Result<(), ContextError>> + '_>>;
このリポジトリは学習用だしこの書き方で全然良いと思っていますが、
[async-trait](https://github.com/dtolnay/async-trait) というcrateを使うとトレイトの中でも async fn 使えて便利ですよとひけらかしてみます（知ってたらごめんなさい）

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +trait Context: Debug + Send + Sync {
traitが `Debug` を求めるのはまあまあ制約が強い（あまり見ない）気がします。

trait の中で debug print しているような箇所があれば求めざるを得ないですが、そうでもないなら `Debug` は外して良いと思います。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +trait Canceler: Debug + Send + Sync {
ここも Debug は外せるなら外して良いと思います。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    fn cancel(&self, remove_from_parent: bool, error: ContextError);
`remove_from_parent` と `error` の役割がわからないので、[doc comments](http://doc.rust-jp.rs/rust-by-example-ja/meta/doc.html#doc-comments) がほしいところです。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    fn done(&self) -> Pin<Box<dyn Future<Output = Result<(), ContextError>> + '_>>;
Goの方を見るとCanceler相当はあくまでもキャンセルだけが機能で、 この `done` 相当のものはなさそうに見えます。
必要そうならdoc commentがほしいところです。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +struct WithCancel {
[nits\ 名称は `ContextWithCancel` でどうでしょうか？
Goでは `context.WithCancel` とか書く文化なのかもしれませんが、Rustではmodule名なしで `WithCancel` とだけ書くことも多く、その場合contextなのか何なのかあんまりわからないように感じるからです。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    children: Vec<Arc<dyn Canceler>>,
ちょっとわかってないだけかもしれませんが、 `Vec<ArcMutex<dyn Canceler>>>` でなくて大丈夫ですか？

`WithCancel` から `ContextBody` への可変参照を得ても、 `children` の中の `Canceler` への可変参照は得られないように見えまして。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    pub fn new<C: 'static + HasContextBody + Context + Debug>(
ここも Debug 不要なら取りたいです。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    let (ctx, canceler) = WithCancel::new(Background::new()); // context.Background()に関してあまり理解できていない
マージ前には理解して `// context.Background()に関してあまり理解できていない` のコメントは取り去りたいところです。

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +impl Context for WithCancel {
WithCancelがContextなのは何かモデリングがおかしいような気がします 🤔 
Goではただのfuncですし: https://golang.org/pkg/context/#WithCancel

2021-05-07 12:23 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +impl Canceler for WithCancel {
WithCancelがCancelerなのもおかしい気が...
Cancelerはtraitではなくただのstructで良さそうな気がします（Goではただの関数ですし）。

2021-05-07 12:26 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    let (ctx, canceler) = WithCancel::new(Background::new()); // context.Background()に関してあまり理解できていない
ここ、コメント取り忘れでした。

修正します。

2021-05-07 12:29 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +impl Context for WithCancel {
https://golang.org/pkg/context/#WithCancel この関数は返り値が`Context`(interface) という風になってますが。
実態は[`witCancel`](https://golang.org/src/context/context.go?s=8419:8483#L344)という構造体になっています。
これが、`Context` interfaceを実装しているみたいです。

なので、この実装自体は則しているのかなと思っています。

2021-05-07 12:31 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +impl Canceler for WithCancel {
ここに関してはそうですね、ここは`Canceler`ではなくて`CancelPropergate`(childrenにCancelを流すことができる)な気がしますね。
修正します。

2021-05-07 12:32 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +impl Context for WithCancel {
> Goではただのfuncですし: https://golang.org/pkg/context/#WithCancel

Goだとコンストラクタを構造体と同じ名前の関数で書くみたいで混乱するんですよね。

2021-05-07 12:35 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    fn done(&self) -> Pin<Box<dyn Future<Output = Result<(), ContextError>> + '_>>;
調べてみて導入しようか悩みましたが、学習用ということで苦しんでみました😁

2021-05-07 12:39 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +#![allow(dead_code)]
了解です、そちらの方針で行きましょう。

2021-05-07 12:40 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    fn deadline(&self, deadline: Instant, ok: bool);
たしかに、ここはmutのほうが良いですね。
というのもあるのですが、上の必要な部分だけ実装する方針でしたら、そもそも消してしまったほうが良いかもしれないです。

2021-05-07 12:40 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    fn value(&self, key: &ContextKey) -> Result<Arc<dyn Any>, ContextValueError>;
`value`を将来的にどのように取り回して行くかによってしまうと思うのですが。
Goで想定されているレベルで取り回すには`Arc`が必要だと思ってこちらにしています。

2021-05-07 12:42 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    fn cancel(&self, remove_from_parent: bool, error: ContextError);
`error`に関しては書こうかと思います。
`remove_from_parent `に関してはどちらかと言うとGoのGCまわりのために入れてる感じがあるので一旦消してしまおうかと思います。

2021-05-07 12:43 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +struct WithCancel {
たしかにそうですね。
変更します。

2021-05-07 12:45 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    children: Vec<Arc<dyn Canceler>>,
現状だとchildren経由で触るのは `HasContextBody::context_body`から得られるMutexの中の値だけなためここにはMutexはいらないと判断しています。

2021-05-07 19:50 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    fn value(&self, key: &ContextKey) -> Result<Arc<dyn Any>, ContextValueError>;
自分の勉強のためのコメントです。
&dyn Any にはできなくて Arc<dyn Any> にはできること（の中で value() の返り値として有益なこと）って何でしょうか？

2021-05-07 20:03 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +impl Context for WithCancel {
ああなるほど。理解しましたありがとうございます！

2021-05-08 14:30 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    fn value(&self, key: &ContextKey) -> Result<Arc<dyn Any>, ContextValueError>;
> &dyn Any にはできなくて Arc にはできること（の中で value() の返り値として有益なこと）って何でしょうか？

一番は返ってくるデータを保持していた構造体やその参照より長いライフタイムが保持できることだと思っています。
今回は`その参照より長いライフタイムが保持できる`というのが必要になってくるのかなと思っています。

2021-05-08 21:13 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    fn value(&self, key: &ContextKey) -> Result<Arc<dyn Any>, ContextValueError>;
確かに！ありがとうございます 🙏

2021-05-08 22:18 UTC, laysakura requested changes
各オブジェクト (struct, trait, enum) の機能とそれらの関連が分かりづらいので、ドキュメントがほしいです。

`main.rs` から `context.rs` などに移設して、その先頭に `//! ...` の形で各オブジェクトの関連を書き、
それぞれのオブジェクトに `/// ...` の形でオブジェクト自体の説明を書く

ようにお願いできないでしょうか？

---

また、今回

- コンテキストの key/value 機能
- コンテキストがツリーを構成する機能・親が子にキャンセルを伝播させる機能

は使ってないように思います。

これらの処理はコードから削除し、libに移す際に（テストやexampleと共に）追加するのもありだと思います。

2021-05-08 22:18 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +enum ContextKey {}
contextのキーはenumで表すものでしょうか？
キーに（型レベルの）種類があると便利な例が思いつかず。

生の `&str` や `struct ContextKey(String)` で十分に感じます。

2021-05-08 22:18 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +}
エラー型を定義するときは `std::error::Error` を impl するのが良いです。

2021-05-08 22:18 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    parent: Option<Arc<dyn Context>>,
ContextBodyを木構造とみなしたときに、親・自分・子のデータ型が大きく異なるのが気になります（同じtraitの別impl程度なら気にならない）。
特に、CancelPropagateはContext実装をしていないと思いますが、意図は合っていますか？

2021-05-08 22:18 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +struct ContextBody {
名前から機能が想像しづらいです。ContextTreeとかだとどうでしょうか？

2021-05-09 15:43 UTC, yuk1ty reviewed
`Context` トレイトにまつわる実装は、ちょっと実装が長くなってきてしまっているのと、別ファイルで細かく実装の意図／場合によっては簡単な利用例をコメントとして欲しいかなと思いました。コメントやdocは日本語でよいですー！

2021-05-10 11:55 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +enum ContextKey {}
こちらに関しては、

https://golang.org/src/context/context.go?s=8419:8483#L153

ここの実装に合わせてる感じになります。`interface {}`は`Any`なのですがそこまで自由にするのは微妙なので`enum`にしています。

ちなみに、GoのContextは[ここ](https://golang.org/src/context/context.go?s=8419:8483#L353)のように定数のcontextKeyでしていするとContext自体が返ってくるような仕様になっているみたいです。

2021-05-10 12:05 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    parent: Option<Arc<dyn Context>>,
こちらは、`parent`に対して行いたい操作と`children`に対して行いたい操作が違っているのでこのようになっています。

> 特に、CancelPropagateはContext実装をしていないと思いますが、意図は合っていますか？

こちらに関しては、`trait CancelPropagate`は`trait Context`を継承していないので、`dyn CancelPropagate`は`trait Context`を実装していない可能性があります。

こちらに関しては例えば`struct EmptyContext`は`trait CancelPropagate`を実装する必要は無いと考えています。(自分自身は`cancel`出来ないし、親もいないので)
また、そうしておくことによって、EmptyContextのような親を持たないことを保証したい型を静的保証することが出来たりします。

2021-05-10 12:07 UTC, higumachan commented
@yuk1ty 

> `Context` トレイトにまつわる実装は、ちょっと実装が長くなってきてしまっているのと、別ファイルで細かく実装の意図／場合によっては簡単な利用例をコメントとして欲しいかなと思いました。コメントやdocは日本語でよいですー！

> > Goの標準ライブラリにあるようなものを実装した場合には（他で使うか否かにかかわらず） lib に置いて良いと思います。
ただし lib に置くからには最低限 doc test か unit test はほしいところです。
>
> unit testとかは`WithValue`とかの他のコンテキストも実装してからやったほうが良さそうだと思います。
> 一旦このPRはこのコードでマージして頂いて別PRでlibへの分割しようかと思うのですがどうでしょうか？


こちらで、一旦PRをマージしたあとに別PRで分割しようかと考えていたのですが、このPRでやったほうが良いでしょうか？

2021-05-11 13:22 UTC, yuk1ty commented
> こちらで、一旦PRをマージしたあとに別PRで分割しようかと考えていたのですが、このPRでやったほうが良いでしょうか？

了解です、では、別PRで行きましょう！！🙂

2021-05-12 05:15 UTC, laysakura commented
@yuk1ty からreview requestもらいましたが、 @higumachan もう review ready でしょうか？
readyになったら遠慮なくrequestボタン押してください 👍

2021-05-12 10:34 UTC, higumachan commented
@laysakura まだ、コメントを付けている途中ですのでもう少々お待ち下さい。

本日中にreadyにします。

2021-05-12 14:59 UTC, higumachan commented
@laysakura 

readyになりました。(pending状態だと再度はrequestボタン押せないみたいです。)


> また、今回
> 
> コンテキストの key/value 機能
> コンテキストがツリーを構成する機能・親が子にキャンセルを伝播させる機能
> は使ってないように思います。
> 
> これらの処理はコードから削除し、libに移す際に（テストやexampleと共に）追加するのもありだと思います。
> 
> 

こちらなんですが、難しい判断だと思いますが、そこまで削除してしまうと現状の実装している理由がわからなくなる(treeにしてる理由とか)気がするので一旦ここらへんはそのままでいこうかと思います。

2021-05-13 00:30 UTC, laysakura commented
https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/35#discussion_r629301179 への返答です。

> こちらに関しては、trait CancelPropagateはtrait Contextを継承していないので、

自分がわかっていないのは、 `CancelPropagate` がなぜ `Context` を継承（というか impl を強制）しないのかという点です。

https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/35/files#diff-270258bfac132ecb293692effb59662a6f94f74e98fac6ef1489e3272cefe053R116-R117

にも「子要素に対してCancelを伝播する事ができるContext」と書いてあり、 `CancelPropagate: Context` が正しい関係なのかなと感じました。

2021-05-13 00:38 UTC, laysakura requested changes
自分のタイムリミットが来たので途中までのレビューを送信します。
~~後でまた見直して追加するかもしれませんが、見直しても何もなければそのままにしておくので、対応はいつでも進めておいていただければ 🙆‍♀️ ~~

→ コメント追加しました。

2021-05-13 00:38 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +enum ContextKey {}
※前提として、自分はGoに合わせることはあまり大事ではないと思ってレビューをしています。

> ここの実装に合わせてる感じになります。interface {}はAnyなのですがそこまで自由にするのは微妙なのでenumにしています。

まだいまいちわかってないのですが、

- この enum は将来的にどのような variant を持つ想定ですか？
- keyに「ちょっとは制限するが色んな型を対応させたい」場合、enum よりも trait を使い、その trait を実装した型は key になるとしたほうが自然に感じますが、どうでしょうか？

2021-05-13 02:24 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +            .value(key)
単純に全然わかってないだけですが、親にvalueを聞きに行くのはそういうものなんですか？
`ContextWithCancel` が直接 key-value を持たないのはなぜですか？

ContextTree における key-value が「子は自分の祖先の key-value が見える」「親は子孫の key-value が見えない」という仕様なら理解できます。

2021-05-13 02:24 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +            .expect("親がすでに開放されています")
これはどういうケースで発生しますか？

2021-05-13 02:24 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +trait HasContextTree {
このtraitの存在理由はなんですか？

ちょっと trait が多く、互いの関係がドキュメントからわからないため目が回ってしまい...

2021-05-13 07:49 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +            .expect("親がすでに開放されています")
基本的には発生しないとは思います。

`a -> b`のような親子関係があったとして、
bが変数に束縛されていたとして、aがdropした場合に起きます。

2021-05-13 07:58 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +            .value(key)
> ContextTree における key-value が「子は自分の祖先の key-value が見える」「親は子孫の key-value が見えない」という仕様なら理解できます。

こちらはその仕様になっています。

それに加えて、ContextのTreeにおけるノード(Contextの実装)は単一の機能 (valueを持つ, cancelできる, deadlineを持つ)を持ちます。

`ContextWithCancel`は「cancelできる」という単一の機能をもつノードですので自分でValueは持たない感じです。
コメントで少しだけ出ている`ContextWithValue`というのがValueを持つようなノードになる予定です。

2021-05-13 08:07 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +enum ContextKey {}
> この enum は将来的にどのような variant を持つ想定ですか？


enum ContextKey  {
    String(String),
    WithCancel,
    WithValue,
    WithDeadline,
}

のようになります。

> keyに「ちょっとは制限するが色んな型を対応させたい」場合、enum よりも trait を使い、その trait を実装した型は key になるとしたほうが自然に感じますが、どうでしょうか？

こちらは、Goの`interface {}`の使い所がどう見ても(string | int)というような直和型だったのでenumにしています。加えてintの使いかたもContextの実装ごとに定数値を割り振っている形なのでintではなく`WithCancel`などで表現しています。

2021-05-13 23:15 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +enum ContextKey {}
> Goのinterface {}の使い所がどう見ても(string | int)というような直和型だった

ごめんなさい。この論拠がわかりません。
https://go-tour-jp.appspot.com/methods/9 あたりを見るに、私には直和型でなくtraitのほうが近いように思えます。
traitにしておいたほうが、ユーザーが定義した型をContextKeyとして使えるように拡張できるメリットもあります。

> 加えてintの使いかたもContextの実装ごとに定数値を割り振っている形なのでintではなくWithCancelなどで表現しています。

ちょっとこれもわかりませんでした。もしGoの特定のコードを挿しているのであればポインタのリンクを貼っていただければ助かります。

2021-05-13 23:17 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +            .value(key)
ありがとうございます。そのあたりは重要な情報ですので、是非struct / traitのコメントに書いてください。

2021-05-13 23:19 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +            .expect("親がすでに開放されています")
ContextTreeの使われ方的に発生しないことが想定されるなら、expectの中の文字列は

```suggestion
            .expect("親から先に開放されることはない想定")
```

のように書いていたほうが、読み手にとってやさしいです。

2021-05-13 23:22 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    parent: Option<Arc<dyn Context>>,
> こちらに関しては、trait CancelPropagateはtrait Contextを継承していないので、

自分がわかっていないのは、 CancelPropagate がなぜ Context を継承（というか impl を強制）しないのかという点です。

https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/35/files#diff-270258bfac132ecb293692effb59662a6f94f74e98fac6ef1489e3272cefe053R116-R117

にも「子要素に対してCancelを伝播する事ができるContext」と書いてあり、 CancelPropagate: Context が正しい関係なのかなと感じました。

2021-05-14 02:40 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +    parent: Option<Arc<dyn Context>>,
確かに、そのとおりですね。

CancelPropagateがContextを継承していなかったので単純にContextのメソッドを利用していない(実装上は必要なかった)からになっていました。
しかし、概念上ではCancelPropagateはContextのsub traitになっているのでこちらは変更したいと思います。

2021-05-14 03:28 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +enum ContextKey {}
> ちょっとこれもわかりませんでした。もしGoの特定のコードを挿しているのであればポインタのリンクを貼っていただければ助かります。

こちらに関しては以下になります。

https://golang.org/src/context/context.go?s=8419:8483#L288

https://golang.org/src/context/context.go?s=8419:8483#L353

> ごめんなさい。この論拠がわかりません。
> https://go-tour-jp.appspot.com/methods/9 あたりを見るに、私には直和型でなくtraitのほうが近いように思えます。
> traitにしておいたほうが、ユーザーが定義した型をContextKeyとして使えるように拡張できるメリットもあります。

https://golang.org/src/context/context.go?s=8419:8483#L558

こちらを見ると僕が勘違いしていたみたいです、Goの実装ではただ`==`が実装されていれば良いみたいですね。(Goだと任意の型の間に`==`が定義されるのかな？)

そこに来ると、`trait ContextKey`をどう定義するのかが難しくなりますね。

2021-05-16 08:17 UTC, higumachan commented
@laysakura 

レビュー依頼出させてもらいました。

主な変更点は

- `trait HasContextTree`を`trait TreeContext`として`trait Context`のsub traitとしあくまで`trait Context`の1実装として強調する用に整理
- ContextKeyをtrait化に挑戦して失敗した旨をFIXMEとしてコメントに記載

2021-05-16 22:28 UTC, laysakura requested changes
FIXMEの箇所に関してだけ変更要求を出しました。
このPRとしてはこの次で最後の修正&コメント往復として、次回以降にlib移しで良いかなと思います。

2021-05-16 22:28 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +///     fn dynamic_equal(&self, other: &dyn Any) -> bool {
other には Any ではなく Self を取ったほうが良いのではないでしょうか？
もっと言うと、比較演算を自前実装せず、 `ContextKey: PartialEq + Sized` 程度にしておいて、  `eq()` に任せれば良いのではないでしょうか？

こんなにAnyが出てきているのはGoの `interface {}` に囚われすぎているのかなと思います。
そうだとしたら、Goに詳細なインターフェイスまで合わせる必要はないと思います。
Goからはあくまでもアイディア（要件）を借りる程度にして、その要件をRustでシンプルに実装するための設計を trait/struct 単位でちゃんと考えたら良いと思います。

2021-05-16 22:28 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +    pub trait CancelPropagate: Send + Sync + TreeContext {
[nits] `Send + Sync` は祖先の `Context` から強制されるので不要です。

2021-05-17 05:04 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +///     fn dynamic_equal(&self, other: &dyn Any) -> bool {
> other には Any ではなく Self を取ったほうが良いのではないでしょうか？
もっと言うと、比較演算を自前実装せず、 ContextKey: PartialEq + Sized 程度にしておいて、 eq() に任せれば良いのではないでしょうか？

こちらはotherは`&dyn Any`(コンパイルエラーが出なければ`&dyn ContexyKey`)である必要があり、`PartialEq::eq()`には任せられないという認識をしております。

現状の実装だと`trait ContextKey`は`trait ContextKey`が実装されている**全ての型同士**の等価性を検証できる必要があります。

otherに`Self`を利用する場合は`trait PartailEq<Self>`と同じになり、ある`trait ContextKey`を実装した型同士のみの等価性の検証しか出来なくなってしまいます。(本当はotherは`&dyn Any`ではなく`&dyn ContexyKey`だと思いますが、こちらはコンパイルエラーが出ますね)
結果として、RTTIを利用して型情報での等価性を検証した後に値の等価性を検証している形になっています。

> こんなにAnyが出てきているのはGoの interface {} に囚われすぎているのかなと思います。
そうだとしたら、Goに詳細なインターフェイスまで合わせる必要はないと思います。
Goからはあくまでもアイディア（要件）を借りる程度にして、その要件をRustでシンプルに実装するための設計を trait/struct 単位でちゃんと考えたら良いと思います。

こちらは僕もそう思っております。
その僕の中での回答が`enum`を利用した実装です。

2021-05-17 05:28 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +///     fn dynamic_equal(&self, other: &dyn Any) -> bool {
丁寧に返答いただきありがとうございます。

> こちらは僕もそう思っております。
> それの僕の中での回答がenumを利用した実装です。

了解です。
一方で自分としてはまだ、何故 ContextKey が trait ではだめなのかがわからない状況です。
当該コードに触れた時間が私のほうが短いので、見落としがあればご指摘ください。

```rust
trait ContextKey: Eq + Any + Sized {
```

と (Any を入れて) 定義しようとしているから話がややこしくなっているのではないかと思っています。

```rust
trait ContextKey: PartialEq + Sized {}
```

とだけ定義し、キーとして使いたい型（ただしPartialEqである必要あり）に

```rust
impl ContextKey for i32 {}
```

としてあげるのでは何が不足でしょうか？

2021-05-17 06:52 UTC, higumachan commented on chapter4/src/4_2_5/main.rs
> +///     fn dynamic_equal(&self, other: &dyn Any) -> bool {
前提として今回書いている`Eq`に関しては`PartialEq`にしても問題ないと思っています。

やりたいこととしては、
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d8d97c8edc09a35557a9b07234ff1eeb
こんな感じで仮定させていただきます。

こちらに関しては

```rust
trait ContextKey: PartialEq + Sized {}
```

こちらですと

```rust
impl ContextKey for i32 {}
impl ContextKey for String {}
```

としたときに、

```rust
let v1 = 100;
let v2 = "test".to_string();

println!("{}", v1 == v2);  // compile error
```

とすることが出来ないのが問題だと考えています。
理由としては`trait PartialEq`は`trait PartialEq<Self>`となっていることが原因です。

今回やりたいことは、ContextKeyをimplした型全てとの等価性の検証です。
これをシンプルに考えると、
```rust
trait ContextKey: PartialEq<&dyn ContextKey> + Sized {}
```

とするのですが、これは

1. ライフタイムまわりの整理が大変
2. ContextKeyとして利用したい型全てに対して`PartialEq<&dyn ContextKey>`を実装する必要がある。

という点であまり現実的ではないと考えています。

そこで、`trait ContextKey`に`dynamic_equal`という

1. 別の型ならfalse
2. 同じ型なら`PartialEq::eq`に処理を委譲

というようなメソッドを定義することで実現しています。
このように定義することにより、`PartialEq`と`Any`が実装されていれば自動的にContextKeyが実装されるように出来ます。

`1の別の型`かどうかを検証するためにRTTI(`Any::type_id()`)を利用するのですが、それが定義されているのが`trait Any`になるので、ContextKeyがAnyを継承しなければいけない理由になります。

2021-05-17 07:01 UTC, laysakura commented on chapter4/src/4_2_5/main.rs
> +///     fn dynamic_equal(&self, other: &dyn Any) -> bool {
こちらの説明で完全に理解しました。ありがとうございます。

FIXMEの解消を別PRでやるということで了解です。

2021-05-17 07:02 UTC, laysakura approved these changes
[nits] コメントは残っていますが、そこは修正せずマージしてもOKです 🙆‍♀️

2021-05-17 12:31 UTC, yuk1ty commented
長い間お疲れさまでした😃
ありがとうございましたー！
goroutine の箇所は tokio で問題なさそうですね！

2021-05-17 12:31 UTC, yuk1ty approved these changes

2021-05-17 12:32 UTC, yuk1ty commented
以前やり取りしたとおり、他にも取り組む必要がある内容がある認識ですので、こちらはもうマージしてしまいますね。引き続き、修正等できそうでしたらよろしくお願いします。

2021-05-17 12:32 UTC, merged