add 2_4_5
yuk1ty/learning-systems-programming-in-rust pull request #38
Opened 2021-05-01 17:53 UTC by shnmorimoto

#5 

一旦実装してみましたが、下記少し悩んでいます。
- gzipのライブラリとして、[flate2](https://docs.rs/flate2/1.0.20/flate2/)が適当か。
- `io.MultiWriter` 相当のものが見つからなかったので、自前でFileをwrapするものを実装したが、他に良い方法がないか、もしくはskipしたほうがよいか？

2021-05-01 21:29 UTC, laysakura commented
> io.MultiWriter 相当のものが見つからなかったので、自前でFileをwrapするものを実装したが、他に良い方法がないか、もしくはskipしたほうがよいか？

簡易的なものなら MultiWriter はシンプルに作れます。

```rust
struct MultiWriter(Vec<Box<dyn Write>>);

impl MultiWriter {
    fn new(writers: Vec<Box<dyn Write>>) -> Self {
        Self(writers)
    }
}

impl Write for MultiWriter {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        for w in &mut self.0 {
            // Using `Write::write` is more straightforward but
            // it sometimes (especially when buf is large) writes only part of buf.
            // To align bytes written for all writers (self.0), here uses `Write::write_all`.
            w.write_all(buf)?;
        }
        Ok(0)
    }

    fn flush(&mut self) -> io::Result<()> {
        for w in &mut self.0 {
            w.flush()?;
        }
        Ok(())
    }
}
```

2.8 の Q3 を担当していてそこでも MultiWriter を使う必要があるから実装しました。

こんなふうに「標準ライブラリに入ってないしわざわざ外部クレート使うほどでもないが、このリポジトリでは共通して使いたい」ものはどうしましょうね？
Issueを立てておきます。

2021-05-01 21:46 UTC, laysakura commented
> gzipのライブラリとして、flate2が適当か。

rust-lang organization 配下のcrateですし、 `std::io::Write` トレイト実装をしたエンコーダーがありこの本の題材にもマッチしやすいので、私は適当だと思います。

自分が担当している 2.8 Q3 でもgzip必要なので、flate2を使うことにします。
もしベターなものがありそれを使うということになったら追従します 🏃

2021-05-01 22:34 UTC, laysakura requested changes

2021-05-01 22:34 UTC, laysakura commented on chapter2/src/2_4_5/main.rs
> +        self.w.write(buf)?;
複数の対象に `write` する場合は、2つの `write` で書き込む長さが異なる可能性に配慮する可能性があります。
[こちらの MultiWriter](https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/38#issuecomment-830697268) では `write_all` を使うことにしています。

2021-05-01 22:34 UTC, laysakura commented on chapter2/src/2_4_5/main.rs
> +    buffer.flush()?;
[nits] `write() ; flush()` の代わりに `write_all()` でも良さそうです。

2021-05-01 22:34 UTC, laysakura commented on chapter2/src/2_4_5/main.rs
> +    writer2.write(b"gzip.Writer example\n")?;
flush() をするか write_all() にしないと、全バイトが書き込まれる保証がないと思います。

2021-05-01 22:34 UTC, laysakura commented on chapter2/src/2_4_5/main.rs
> +    T: Write,
[nits] 型パラメータの名前もある程度はわかりやすいものが好ましいかと思います。 `T` は割と何でもありなときに使い、 `Write` に対しては `W` のほうが良いかなと思います。

2021-05-02 04:10 UTC, shnmorimoto commented on chapter2/src/2_4_5/main.rs
> +        self.w.write(buf)?;
なるほど。writeの場合は自前ですべて書き込まれたか管理する必要があるのですね。
ありがとうございます。今後このようなケースではwrite_allを利用するに致します。

2021-05-02 04:11 UTC, shnmorimoto commented on chapter2/src/2_4_5/main.rs
> +    writer2.write(b"gzip.Writer example\n")?;
ありがとうございます！write_all()に修正致します。

2021-05-02 04:11 UTC, shnmorimoto commented on chapter2/src/2_4_5/main.rs
> +    buffer.flush()?;
ありがとうございます。一旦write_all()で統一しようと思います。

2021-05-02 04:12 UTC, shnmorimoto commented on chapter2/src/2_4_5/main.rs
> +    T: Write,
確かにそちらのほうがわかりやすいですね。ありがとうございます。

2021-05-02 04:18 UTC, shnmorimoto commented
@laysakura レビューありがとうございます。

> 簡易的なものなら MultiWriter はシンプルに作れます。

おぉ、こんなにシンプルに定義できるのですね。ありがとうございます。

> こんなふうに「標準ライブラリに入ってないしわざわざ外部クレート使うほどでもないが、このリポジトリでは共通して使いたい」ものはどうしましょうね？
Issueを立てておきます。 → 立てました: #39

lib を導入する予定とのことなので、そちらに定義され次第、利用するように修正致します。

> rust-lang organization 配下のcrateですし、 std::io::Write トレイト実装をしたエンコーダーがありこの本の題材にもマッチしやすいので、私は適当だと思います。
>
> 自分が担当している 2.8 Q3 でもgzip必要なので、flate2を使うことにします。
> もしベターなものがありそれを使うということになったら追従します runner

承知致しました。一旦flate2で進めようと思います。

2021-05-03 21:43 UTC, laysakura commented
@shnmorimoto https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/51 で lib::io::MultiWriter が入ったのでお知らせします 🔈

2021-05-04 12:42 UTC, shnmorimoto commented
@laysakura ありがとうございます！修正完了致しました！

2021-05-04 14:10 UTC, shnmorimoto commented
コンフリクト修正したら、少し変なコミットログになってしまったので、修正してpushしなおしました。🙏

2021-05-04 18:41 UTC, laysakura approved these changes
✨ 👏

2021-05-05 13:22 UTC, yuk1ty approved these changes

2021-05-06 10:39 UTC, yuk1ty commented
5/7 23:59 までオープンしておきます！

2021-05-07 15:00 UTC, merged