add 3.6.2
yuk1ty/learning-systems-programming-in-rust pull request #49
Opened 2021-05-03 09:16 UTC by yuk1ty

3.6.2 を実装します。Rust には `scanf` 関数はなかったはずで、実現するためにはマクロか自前で関数を定義するかといった実装が必要になります。

飛ばしてもよかったですが、参考程度に実装を用意しておきます。`Reader` を使えてないので、あまりいい実装ではないかもしれません。他にいい手をご存知の方いらっしゃいましたら教えて下さい🙇‍♀️

## Go のコード
- https://play.golang.org/p/NY4io1CvALw

2021-05-05 10:03 UTC, laysakura requested changes
細かい点だけコメントしました。

> Rust には scanf 関数はなかったはずで、実現するためにはマクロか自前で関数を定義するかといった実装が必要になります。

そう思います。

> Reader を使えてないので、あまりいい実装ではないかもしれません。

十分かと思います。
もちろんマクロの中で `$string:expr` の箇所を Reader にすることもできるでしょうが、あまりにもGoに合わせることが目的になってしまうのも本質的でないと思いますし、コードコメントで意図が丁寧にに書かれていると思います。

2021-05-05 10:03 UTC, laysakura commented on chapter3/src/3_6_2/main.rs
> +fn main() -> std::io::Result<()> {
ここはResult不要ですね。clippyかけると↓が出ます。

```
this function's return value is unnecessarily wrapped by `Result`
`#[warn(clippy::unnecessary_wraps)]` on by default
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_wraps
```

2021-05-05 10:03 UTC, laysakura commented on chapter3/src/3_6_2/main.rs
> +/// - [scan_fmt](https://github.com/wlentz/scan_fmt): 同様に scan_fmt マクロが存在する。
structやらfnではなくファイルに紐付くコメントは `//!` で記載します。
see: https://doc.rust-jp.rs/rust-by-example-ja/hello/comment.html

2021-05-05 14:43 UTC, yuk1ty commented
PTAL!

2021-05-05 21:04 UTC, laysakura approved these changes
👍 👍 👍

2021-05-06 10:40 UTC, yuk1ty commented
5/8 23:59 までオープンしておきます

2021-05-09 01:47 UTC, merged