ファイルの変更監視 (10.1節) のexampleコードの追加
yuk1ty/learning-systems-programming-in-rust pull request #74
Opened 2021-05-09 07:02 UTC by denjiry

## 対象の Issue
#69 
## 動作確認結果
- ファイル変更側のログ
``` bash
$ touch test.txt
$ 
```

- 監視側のログ
``` bash
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.47s
     Running `/home/denjiry/code/rust/sysrust/target/debug/10_1`
RawEvent { path: Some("/home/denjiry/code/rust/sysrust/chapter10/./test.txt"), op: Ok(CREATE), cookie: None }
RawEvent { path: Some("/home/denjiry/code/rust/sysrust/chapter10/./test.txt"), op: Ok(CHMOD), cookie: None }
RawEvent { path: Some("/home/denjiry/code/rust/sysrust/chapter10/./test.txt"), op: Ok(CLOSE_WRITE), cookie: None }
$ 
```

2021-05-09 21:48 UTC, laysakura requested changes
nightlyの箇所だけ必要に応じて修正をお願いします。
それ以外のコメントはコード修正は必須ではないです。

2021-05-09 21:48 UTC, laysakura commented on chapter10/rust-toolchain
> +nightly
nightlyはどこで必要ですか？
仮にこの問題だけで必要だとしても、10章全体に効力が及ぶのでちょっとやり方は考えたいです。
（自分で試した感じ10.1もstableで動きそうでした）

2021-05-09 21:48 UTC, laysakura commented on chapter10/src/10_1/main.rs
> +use notify::Watcher as _;
[質問] `as _` の書き方は初めてみました 👀 
trait有効にするためだとは思いますが、自分は `use notify::Watcher;` とだけやってしまいます。
この書き方は世の中で結構するものなんですか？

2021-05-09 21:48 UTC, laysakura commented on chapter10/src/10_1/main.rs
> +    let mut counter = 0u32;
[nits] 利用箇所に近いところでの定義が読みやすいので、whileの直前に持ってきたほうが良さそうです。

また、 `for _ in 0..3 {` だとカウンタ変数要らずより良いと思います。

2021-05-10 11:19 UTC, denjiry commented on chapter10/rust-toolchain
> +nightly
すみません、mainブランチのReadme見て勘違いしてました…僕の手元でもstableで動作確認できたのでdeleteします。

2021-05-10 13:23 UTC, denjiry commented on chapter10/src/10_1/main.rs
> +use notify::Watcher as _;
[underscore import](https://doc.rust-lang.org/reference/items/use-declarations.html#underscore-imports)といって、トレイト以外ではやらない書き方なので、個人的に好きな書き方でした。ですがTwiiterで聞いたところ、複数の同じ名前のトレイトを使用する際に回避策として使うことができるようです。
cf. [[Rust] anyhow::Context を use したいが名前が被ってしまうときの解決策 -> impl-only-use](https://zenn.dev/magurotuna/articles/2c4037b75f7e51)

2021-05-10 14:21 UTC, denjiry commented on chapter10/src/10_1/main.rs
> +    let mut counter = 0u32;
そちらのほうがよさそうですね、反映しました！

2021-05-11 22:10 UTC, laysakura approved these changes
💯

2021-05-11 22:10 UTC, laysakura commented on chapter10/src/10_1/main.rs
> +use notify::Watcher as _;
ありがとうございます！勉強になります 📝

2021-05-12 06:23 UTC, denjiry commented
レビューありがとうございます、コンフリクト解消などでできることあればぜひ！（gitのベストプラクティスに詳しくないので適当な手段をサジェストできなくて申し訳ないのですが…）

2021-05-12 06:30 UTC, laysakura commented
このリポジトリはオープン期間というのがあるので、 @yuk1ty がマージするまでの間は待っていて大丈夫です。

[こんな感じ](https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/70#issuecomment-835184892) でオープン期間の終了タイミングが明示されていたら、その前後でコンフリクト解消のpushしておくと親切かと思います 🙆

2021-05-13 15:45 UTC, yuk1ty commented
5/16 23:59 まで開いておきますー！

2021-05-13 15:47 UTC, yuk1ty approved these changes

2021-05-17 12:29 UTC, yuk1ty commented
@denjiry お手数ですが、コンフリクトの解決をお願いできますか？

2021-05-17 17:53 UTC, denjiry commented
`Cargo.lock`だけ必要だったので解決できたと思います！

2021-05-18 01:46 UTC, yuk1ty commented
対応ありがとうございました！マージしますね

2021-05-18 01:46 UTC, merged