ビルド時にキャッシュするフェーズを追加する
yuk1ty/learning-systems-programming-in-rust pull request #88
Opened 2021-05-15 03:04 UTC by yuk1ty

そろそろ章によってはビルド時間が気になるものが出てきたので、キャッシュしてみたい。Github Actions 素人なので他にいい方法あったらコメントください。

## 計測

```
cargo +nightly build -Ztimings
```

代表的な重そうなものは下記。

tokio

![Screenshot 2021-05-15 at 12 04 04](https://user-images.githubusercontent.com/24487281/118346337-a640d580-b575-11eb-8ff4-b72c454bbcc0.png)

syn

![Screenshot 2021-05-15 at 12 04 13](https://user-images.githubusercontent.com/24487281/118346341-ab9e2000-b575-11eb-8db9-1a08e82b52ae.png)

serde

![Screenshot 2021-05-15 at 12 04 47](https://user-images.githubusercontent.com/24487281/118346349-c07ab380-b575-11eb-9930-08a9b5787c8d.png)

2021-05-15 03:26 UTC, laysakura commented
最近の記事だと https://www.fluvio.io/blog/2021/04/github-actions-best-practices/ が参考になります。
キャッシュに関しては以下の2つのことをやっています。

1. `actions/cache@v2` を使い、 `~/.cargo/registry` と `~/.cargo/git` をキャッシュ
  - 誰でもやるやつ
2. [sccache](https://github.com/mozilla/sccache) を使う
  - 頑張ってる

自分のプライベートリポジトリ(1.は元々やっていた)でもこれの真似をしてみたのですが、 9分掛かっていたビルドが7分になりました。
まあ確かに速くはなったのですが、頑張って sccache を入れる（そして将来のトラブルの種を撒く）ほどの効果かというと自分としては疑問に思いました。

---
https://www.fluvio.io/blog/2021/04/github-actions-best-practices/ の記事の貢献はどちらかというと、「lintやらtestのjobでキャッシュとかrustインストールのための命令がかぶりがちだが、それをmatrixにより共通化する」方法を示したところだと思います。
CircleCIなんかだと普通に `commands:` 定義したりYAMLのanchor使ったりして直感的に共通化できるのですが、GitHub Actionsはなんとその両方ともできないのです。
matrixによる共通化は思いつかなかったのでここは非常に恩恵を受けました。

---
ということで、自分としては

- `actions/cache@v2` を使い、 `~/.cargo/registry` と `~/.cargo/git` をキャッシュ

がまずやるべきことかと思います。
sccacheは少なくとも今の段階でやらないで良いんじゃないかな 🤔 
matrix使った共通化は余力があればやってみるのが良いかと思います（もしやるぞとなって私にアサインくれたらシュッとやることもできます）。

2021-05-15 03:29 UTC, laysakura commented
あ、issueだと思ってコメントしてた 🙄 
コードも見ますね。

2021-05-15 03:42 UTC, laysakura requested changes

2021-05-15 03:42 UTC, laysakura commented on .github/workflows/rust.yml
>      steps:
今気づいたのですが、build jobにも https://github.com/yuk1ty/learning-systems-programming-in-rust/pull/88/files?w=1#diff-73e17259d77e5fbef83b2bdbbe4dc40a912f807472287f7f45b77e0cbf78792dR21-R25  これ相当のがないといけないと思います。
（今動いてるのが何でかは正確にはわからない）

2021-05-15 03:42 UTC, laysakura commented on .github/workflows/rust.yml
> +          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
```suggestion
          key: ${{ runner.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ github.job }}-
            ${{ runner.os }}-cargo-
```

をおすすめします。

`restore-keys:` を書くと、「上から順番にキャッシュキーを先頭一致検索して、ヒットした場合はその名前のキャッシュキーに紐づくキャッシュをrestoreする」という動作をします。
`restore-keys:` を書かなければ `key:` に書いたキャッシュキーと完全一致検索をします。

この場合の問題点は、Cargo.lock が変わったらキャッシュを全く見なくなってしまうところです。更新されていないcrateもたくさんあるはずなのでキャッシュからrestoreしたいですね。

それと、キャッシュキーにはjob名を含めるようにしています。job名が含まれないと、「lint jobとbuild jobでできあがった `~/.cargo/registry` と `~/.cargo/git` を両方のjobで奪い合う形でsaveする」という挙動になります。もっというと、 `actions/cache@v2` は `key:` で指定したキーのキャッシュが既に存在する場合、キャッシュの保存を諦める（先勝ち）の方式をとっています。
実際に起こる問題としては、「lint jobのほうが先に完了してキャッシュをするが、lint jobでは引っ張ってくるcrateが少なかった。たくさんのcrateを引っ張ってきたbuild jobはもう後負けになって、キャッシュできなかった」結果、次回走るbuild jobでrestoreしたキャッシュには、build jobが必要とするcrateがあまり入っていない、ということがあります（実際これやらかしたことあります）。

`restore-keys:` の2つ目は、「restoreのときは、job名が同じキャッシュがなければ違うのからとっても良いよ」と指定しています。
健全に全jobが走っているときは恩恵がないのですが、例えば「buildジョブだけ落ち続けているのでbuildジョブのキャッシュはまだできていない」みたいなケースで、せめてlintジョブのキャッシュは使えるようになるという旨味があります。

2021-05-15 05:22 UTC, yuk1ty commented
ありがとうごじます！
sccache今の段階でやらないは同意です！ｗ

2021-05-15 19:25 UTC, laysakura requested changes
一点コメントしました。

追加で確認です。lint jobにはキャッシュの設定をしていないですが、これは意図的でしょうか？
lint は特に遅くなく build は遅いから、という判断はありだと思います。

2021-05-15 19:25 UTC, laysakura commented on .github/workflows/rust.yml
> +          components: rustfmt, clippy
build stepにおいては rustfmt, clippy は不要です。

```suggestion
```

2021-05-16 02:01 UTC, yuk1ty commented
> lint は特に遅くなく build は遅いから、という判断はありだと思います。

rustfmt や clippy は、とくに重いクレートのダウンロードというステップを実行しないのかなーと思ってキャッシュしていませんでした。
ただ、実行時のログを見た限りでは clippy はコンパイルのステップを挟んでいるようだったので、ステップのうちに追加しておきました。

2021-05-16 06:32 UTC, laysakura commented
自分も「clippyはなんかコンパイルしてるしキャッシュは効きそう」くらいの認識しか持ってませんでした 😮 
つけなくても同じ可能性はないとは言い切れませんね... それでもつけておけば良いと思います！

2021-05-16 06:33 UTC, laysakura approved these changes
お疲れさまでした 🍵

2021-05-16 08:54 UTC, merged